#!/usr/bin/python3
def raise_exception_msg(message=""):
    """Raising the name error"""
    raise NameError(message)
